# -*- coding: utf-8 -*-
"""train_cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h5JaDIfpoNQZYeix1WP56tFn_eyqdOHY
"""

# scripts/train_cnn.py

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from preprocessing import get_train_test_data

def build_cnn_model(input_shape=(32, 32, 3), num_classes=43):
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
        MaxPooling2D(pool_size=(2, 2)),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D(pool_size=(2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(num_classes, activation='softmax')
    ])
    return model

def train_model(data_dir, model_path='../models/traffic_sign_model.h5'):
    X_train, X_test, y_train, y_test = get_train_test_data(data_dir)

    model = build_cnn_model()

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    history = model.fit(
        X_train, y_train,
        epochs=15, batch_size=64,
        validation_data=(X_test, y_test)
    )

    model.save(model_path)
    print(f"Model saved to {model_path}")

if __name__ == "__main__":
    train_model('../data/traffic_signs_dataset/')